global:
  scrape_interval:     10s
scrape_configs:
  - job_name: 'nodejs'
    honor_labels: true
    static_configs:
      - targets: ['backend:3000']
  - job_name: "mongodb"
    honor_labels: true
    static_configs:
      - targets: ['mongo-exporter:9091']
  - job_name: "postgres"
    scrape_timeout: 9s
    honor_labels: true
    static_configs:
      - targets: ['pg-exporter:9092']
  - job_name: "tempo"
    scrape_timeout: 9s
    honor_labels: true
    static_configs:
      - targets: ['tempo:3100']